name: example-project

on:
  push:
    paths:
      - '**/*.html'  # any html file in any (sub)directories
      - '**/*.css'
      - '**/*.js'
  pull_request:
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  screenshot:
    uses: abeslier/screenshot-workflow/.github/workflows/screenshot.yml@force-md-update
    with:  
      input_html_path: "example-project/index.html"
      output_png_path: "example-project/screenshot.png"
      md_path: "README.md"
