name: screenshot

on:
  workflow_call:
    inputs:
      input_html_path:
        default: "index.html"
        required: true
        type: string
      output_png_path:
        default: "screenshot.png"
        required: true
        type: string

permissions:
    contents: write

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # caller's repository
      - uses: actions/checkout@v4
        with:
          repository: abeslier/screenshot-workflow
          path: .screenshot-workflow
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install selenium
      - run: python .screenshot-workflow/screenshot.py ${{ inputs.input_html_path }} ${{ inputs.output_png_path }}
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ inputs.output_png_path }}
          git commit -m "update screenshot"
          git push
